import Head from 'next/head'
import { Inter } from '@next/font/google'
import HeroSection from '../components/HeroSection'
import ProjectSection from '../components/ProjectSection'
import ContactSection from '../components/ContactSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ab Makes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <HeroSection />
        <ProjectSection />
        <ContactSection />
      </main>
    </>
  )
}
